#pragma once

#include "../Common/ALT_TYPE.h"



enum RUNWAY_MARK
{
	RUNWAYMARK_FIRST = 0,
	RUNWAYMARK_SECOND,
};

enum AIRCRAFTOPERATIONTYPE
{
	AIRCRAFTOPERATION_TYPE_NONE = 0,//none
	AIRCRAFTOPERATION_TYPE_LANDING_BEHIND_LANDED,//landing behind langded
	AIRCRAFTOPERATION_TYPE_LANDING_BEHIND_TAKEOFF,//landing behind take off
	AIRCRAFTOPERATION_TYPE_TAKEOFF_BEHIND_LANDED,
	AIRCRAFTOPERATION_TYPE_TAKEOFF_BEHIND_TAKEOFF

};

enum RunwayRelationType
{
	RRT_CONVERGENT,
	RRT_DIVERGENT,
	RRT_CLOSE,
	RRT_INTERMEDIATE,
	RRT_FAR,
	RRT_INTERSECT,
	RRT_SAMERUNWAY,
};

enum RunwayIntersectionType
{
	RIT_NONE,
	RIT_RUNWAY,
	RIT_SPACE,
};

