#pragma once

enum OnboardViewMsg
{
 VM_ONBOARD_VIEWMSG_START = WM_USER +3048,

 VM_ONBOARD_COMPONENT_CHANGE_MODEL =  WM_USER + 3048,
 VM_ONBOARD_COMPONENT_MOVE_MODEL_HEIGHT,
 VM_ONBOARD_COMPONENT_SAVE_MODEL,

 VM_ONBOARD_COMPONENT_NEWSTATION ,
 VM_ONBOARD_COMPONENT_DELSTATION ,
 VM_ONBOARD_COMPONENT_MOVESTATION,
 VM_ONBOARD_COMPONENT_ACTIVE_STATION,
 VM_ONBOARD_COMPONENT_GRID_CHANGE,
 VM_ONBOARD_COMPONENT_EDIT_OPERATION,

 VM_ONBOARD_COMPONET_SCENE_CHANGE,
 VM_ONBOARD_COMPONENT_REDO_UNDO,


 VM_ONBOARD_COMPONENT_EDIT_UNDO,
 VM_ONBOARD_COMPONENT_EDIT_REDO,



 VM_ONBOARD_COMPONET_SHOW_FRAME,
 VM_ONBOARD_COMPONET_SHOW_SHAPE,
 VM_ONBOARD_COMPONET_SHOW_SETION,

 VM_ONBOARD_COMPONENT_MOVE_STATION_POINT,
 VM_ONBOARD_COMPONENT_ADD_STATION_POINT,
 VM_ONBOARD_COMPONENT_DEL_STATION_POINT,
 VM_ONBOARD_COMPONENT_MODIFY_STATION,

 VM_ONBOARD_COMPONENT_MODIFY_STATIONMAP,
 VM_ONBOARD_SECTION_MAP_TRANSFROM_CHANGE, //only the map transform change

 VM_ONBOARD_COMPONET_MODIFY_THICKNESS,
 VM_ONBOARD_COMPONET_MODIFY_LINETYPE,


 //OnBoard  Aircraft Edit MSG
 VM_ONBOARD_AIRCRAFT_CHANGE,
 VM_ONBOARD_MOVESHAPE_XY,
 VM_ONBOARD_MOVESHAPE_Z,
 VM_ONBOARD_SCALE_SHAPE,
 VM_ONBOARD_ROTATE_SHAPE,
 VM_ONBOARD_TRANSFROM_SHAPE,

 VM_ONBOARD_EDITAC_UNDO,
 VM_ONBOARD_EDITAC_REDO,

//on board layout edit msg
 VM_ONBOARD_LAYOUT_CHANGE,
 VM_ONBOARD_LAYOUT_EDITFINISH,
 VM_ONBOARD_LAYOUT_SEATS_CHANGE,
 VM_ONBOARD_DECKMAPCHANGE,
 VM_ONBOARD_ACTIVE_DECK_CHANGE,
 VM_ONBOARD_DECK_HIDESHOW,
 VM_ONBOARD_DECK_CHANGED ,
 VM_ONBOARD_ACLAYOUT_EDIT_OPERATION,
 VM_ONBOARD_SELECTELEMENS_CHANGE,
 VM_ONBOARD_ACLAYOUT_GRID_MODEL_CHANGE,

 VM_ONBOARD_ADD_AIRCRAFTELEMENT,
 VM_ONBOARD_UPDATE_AIRCRAFTELEMENT,
 VM_ONBOARD_DEL_AIRCRAFTELEMENT,
 VM_ONBOARD_SELECT_AIRCRAFTELEMENT,
 VM_ONBOARD_AIRCRAFTELEMENT_DISPLAYPROPERTY,
 VM_ONBOARD_RELOAD_SEATELEMENT,

 TP_ONBOARDLAYOUT_FALLBACK,
 TP_ONBOARD_DATABACK,

//*,*/add  above
 VM_ONBOARD_VIEWMSG_END,
};
