#if !defined(AFX_GATEASSIGNCTRL_H__2F960DB0_D31C_4628_9D3C_CD76931393AF__INCLUDED_)
#define AFX_GATEASSIGNCTRL_H__2F960DB0_D31C_4628_9D3C_CD76931393AF__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CGateAssign wrapper class

class CGateAssign : public CWnd
{
protected:
	DECLARE_DYNCREATE(CGateAssign)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x8425b91b, 0x6246, 0x4ac3, { 0xbf, 0x9a, 0xd9, 0xd5, 0xb0, 0x78, 0xfe, 0x19 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetFlightScheduleFile();
	void SetFlightScheduleFile(LPCTSTR);
	CString GetGateInfoFile();
	void SetGateInfoFile(LPCTSTR);
	CString GetResultFile();
	void SetResultFile(LPCTSTR);
	BOOL GetIsSaved();
	void SetIsSaved(BOOL);

// Operations
public:
	BOOL FlagIsSaved();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_GATEASSIGNCTRL_H__2F960DB0_D31C_4628_9D3C_CD76931393AF__INCLUDED_)
