// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "gateassignctrl.h"

/////////////////////////////////////////////////////////////////////////////
// CGateAssign

IMPLEMENT_DYNCREATE(CGateAssign, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CGateAssign properties

CString CGateAssign::GetFlightScheduleFile()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CGateAssign::SetFlightScheduleFile(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

CString CGateAssign::GetGateInfoFile()
{
	CString result;
	GetProperty(0x2, VT_BSTR, (void*)&result);
	return result;
}

void CGateAssign::SetGateInfoFile(LPCTSTR propVal)
{
	SetProperty(0x2, VT_BSTR, propVal);
}

CString CGateAssign::GetResultFile()
{
	CString result;
	GetProperty(0x3, VT_BSTR, (void*)&result);
	return result;
}

void CGateAssign::SetResultFile(LPCTSTR propVal)
{
	SetProperty(0x3, VT_BSTR, propVal);
}

BOOL CGateAssign::GetIsSaved()
{
	BOOL result;
	GetProperty(0x4, VT_BOOL, (void*)&result);
	return result;
}

void CGateAssign::SetIsSaved(BOOL propVal)
{
	SetProperty(0x4, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CGateAssign operations

BOOL CGateAssign::FlagIsSaved()
{
	BOOL result;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CGateAssign::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
