#pragma once


#include "../Common/ViewMsg.h"


// original macro definition
#if 0
#define VM_SELECT_ALTOBJECT WM_USER + 2048
#define VM_DELECT_ALTOBJECT WM_USER + 2049
#define VM_CHANGENAME_ALTOBJECT WM_USER + 2050
#define VM_NEW_MULT_ALTOBJECTS WM_USER + 2051
#define VM_NEW_SINGLE_ALTOBJECT  WM_USER+ 2052
#define VM_MODIFY_ALTOBJECT WM_USER+ 2503
#define VM_MODIFY_AIRSIDEGROUND WM_USER + 2504

#define MULTIREPORT_SHOWREPORT WM_USER + 2505
#define VM_UPDATA_ALTOBJECTS WM_USER+ 2506
#define AIRSIDEREPORT_SHOWREPORT WM_USER+ 2507

#define VM_MODIFY_HOLDSHORTLINE WM_USER + 2508

#define VM_UPDATE_STRETCH WM_USER + 2509
#define VM_MODIFY_AIRROUTE WM_USER +2510
#define VM_SET_AIRSIDEPLACEMARKER WM_USER + 2511
#define VM_SET_AIRSIDEPLACEMARKERLINE WM_USER + 2512
#define VM_REMOVE_AIRSIDEPLACEMARKER WM_USER + 2513
#define VM_REMOVE_AIRSIDEPLACEMARKERLINE WM_USER + 2514
#define VM_ALIGN_AIRSIDE_MARKS WM_USER + 2515

#define VM_ONBOARD_LAYOUT_DEFAULT WM_USER + 2516

#define VM_MODIFY_AIRPORT WM_USER + 2517
#define VM_ADD_OR_DELETE_AIRPORT WM_USER + 2518

#define VM_GENERATE_REPORT WM_USER+2519

#define VM_GLOBALUNIT_CHANGER WM_USER+2520

#define  AIRSIDEREPORT_DISLISTVIEW WM_USER+2531
#endif