//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AirsideGUI.rc
//
#define IDS_SEPDATAARRARR               1
#define IDS_SEPDATAARRDEP               2
#define IDOK2                           3
#define ID_BUTTON_SAVE                  3
#define IDS_SEPDATADEPDEP               3
#define IDSAVE                          3
#define ID_BTN_SAVE                     3
#define ID_EXPORT                       3
#define IDS_SEPDATADEPARR               4
#define IDR_TOOLBAR_AIRROUTE            4
#define ID_LOAD                         4
#define ID_NEW_NECRELATEDITEM           5
#define ID_DEL_NECRELATEDITEM           6
#define ID_EDIT_NECRELATEDITEM          7
#define IDS_VFR                         8
#define IDS_IFR                         9
#define ID_NEW_AIRROUTE                 10
#define ID_DEL_AIRROUTE                 11
#define ID_EDIT_AIRROUTE                12
#define IDS_CAT                         13
#define IDS_NOFREEZINGPRECITITATION     14
#define IDS_FREEZINGDRIZZLE             15
#define IDS_LIGHTSNOW                   16
#define IDS_MEDIUMSNOW                  17
#define IDS_HEAVYSNOW                   18
#define IDS_LANDINGDISPERF              19
#define IDS_TAXISPDPERF                 20
#define IDS_HOLDSHRTLINEOFF             21
#define IDS_TAKEOFFDISPERF              22
#define IDS_DEICINGTIMECHANGE           23
#define IDS_FLIGHTTYPE                  24
#define IDS_USESTAR                     25
#define IDS_ERROR_TOTAL_PERCENT_EXCEED  26
#define IDS_ERROR_RANGE_INVALID         27
#define IDS_USESID                      28
#define IDS_SPEEDCTRL                   29
#define IDS_SIDESTEP                    30
#define IDS_GOAROUND                    31
#define IDS_EXITPOSITION                32
#define IDS_STANDFAMILY                 33
#define IDS_TAKEOFFPOSITION             34
#define IDS_NAME                        35
#define IDS_NUMBER                      36
#define IDS_SERVICETIME                 37
#define IDS_TVNN_AIRCRAFTS              38
#define IDS_CONDITION                   39
#define IDS_DEPLANEMENTTIME             40
#define IDS_ENPLANEMENTTIME             41
#define IDS_TOWOFFCRITERIA              42
#define IDS_INTERMEDIATESTANDS          43
#define IDS_STAND                       44
#define IDS_TEMPORARYPARKINGCRITERIA    45
#define IDS_DISTANCEFROMARP             46
#define IDS_TIMETOGATE                  47
#define IDS_PERCENT                     48
#define IDS_TVNN_IGNITION               49
#define IDS_LEAVE_ARR_STAND_TIME        49
#define IDS_RETURNTO_STAND_EMPLANEMENT_TIME 50
#define IDS_TIME_LEAVE_ARR_STAND        51
#define IDS_TIME_TOWOFF_CRITERIA        52
#define IDS_RETURN_TO_STAND             53
#define IDS_STAND_PRIORITY              54
#define IDS_TIME_BEFORE_ENPLANEMENT     55
#define IDS_BACKTO_ARR_STAND            56
#define IDS_AIRSERVICETIME              57
#define IDR_MAINFRAME                   128
#define IDR_PRIORITY_ASSIGNMENT         397
#define IDB_COOLTREE                    532
#define IDD_AIRCRAFTRELATED_CATEGORIES  717
#define IDD_AIRSIDE_RUNWAY_ASSIGNMENT   726
#define IDD_DIALOG_SELECT_GSE           999
#define IDD_DIALOG_OCCUPIEDASSIGNEDSTANDCRITERIA 1035
#define IDR_TOOLBAR_ASSIGNEDSTAND_CRITERIA 1039
#define IDC_STATIC_TOOLBARCONTENTER     1290
#define IDC_AS_PLUSDAYEDIT              1785
#define IDC_STATIC_DAY                  1787
#define IDC_STATIC_PLUS                 1788
#define IDC_STATIC_PLUS2                1791
#define IDC_STATIC_PLUS3                1792
#define IDC_PLUSDAYEDIT2                1793
#define IDC_AS_PLUSDAYEDIT1             1793
#define IDC_PLUSDAYEDIT3                1794
#define IDC_STATIC_DAYSTART             1834
#define IDC_STATIC_DAYSTART2            1835
#define IDC_LIST_CONTENTS               1836
#define IDC_TREE_CASES                  1844
#define IDC_LIST_RUNWAY                 1845
#define IDD_AIRSIDE_SIMSETTING          2000
#define IDC_TREE_AIRSIDE_SIMSETTING     2000
#define IDD_DIALOG_AIRROUTS             2001
#define IDC_LIST_AIRROUTE               2001
#define IDR_TOOLBAR_ADD_DEL_EDIT        2002
#define IDC_AIRROUTES_GROUPBOX          2003
#define IDD_DIALOG_SIMSETWEATHER        2004
#define IDR_HTML_DLGRUNWAYASSIGNMENT    2004
#define IDC_ST_INTERSECTION             2004
#define IDC_LIST_DATETIME               2005
#define IDC_ST_GAP                      2005
#define IDD_DIALOG_DYNAMICGATEASSIGN    2006
#define IDC_COMBO_LEADACOP              2006
#define IDC_ASSIGN_LIST                 2006
#define IDC_AD_ASSIGN_LIST              2006
#define IDC_DYNAMIC_RWASSGIN            2006
#define IDC_LIST_RUNWAYASSIGN           2007
#define IDC_COMBO_TRAILACOP             2007
#define IDC_DATETIME_START              2007
#define IDC_AS_DATETIME_START           2007
#define IDC_COMBO_LEADRW                2008
#define IDC_DATETIME_TO                 2008
#define IDC_AS_DATETIME_TO              2008
#define IDC_COMBO_TRAILRW               2009
#define IDC_AS_TIMESET                  2009
#define IDC_COMBO_INTERSECLEAD          2010
#define IDC_LIST1                       2010
#define IDC_RW_AVAILABLE_MODE           2010
#define IDC_LIST_ATCSEPARATION          2010
#define IDC_LIST_DYNAMIC_RW_ASGN        2010
#define IDC_LIST_ATCSEPDATA             2010
#define IDC_LIST_RUNWAYDEF              2010
#define IDC_LIST_ALLFIXES               2010
#define IDC_LIST_INTERSECTIONBLOCKING   2010
#define IDC_LIST_QUEUELENGTH            2010
#define IDC_LIST_SEPARATION             2010
#define IDC_LIST_DATA                   2010
#define IDC_LIST_PARALLELARR            2010
#define IDC_LIST                        2010
#define IDC_LIST_COMPOSIT               2010
#define IDC_LIST_RWEXITSPD              2010
#define IDC_LIST_NEC                    2010
#define IDC_LIST_DEPINTRAIL             2010
#define IDC_LIST_ArrivalInit            2010
#define IDC_LIST_TAKEOFFRUNWAYASSIGN    2010
#define IDC_LIST_ALLNODES               2010
#define IDC_LIST_WAKEVORTEX_BASISITEM   2010
#define IDC_LIST_SIDASSIFNMENT          2010
#define IDC_LIST_WEATHERIMPACTS         2010
#define IDC_LIST_STARASSIGNMENT         2010
#define IDC_LIST_OPEARATION             2010
#define IDC_LIST_RUNWAYEXITANDSTANDFAMILY 2010
#define IDC_LISTBOX_GROUNDROUTE         2010
#define IDC_LIST_CRITERIA_VALUE         2010
#define IDC_LIST_TOWINGROUTES           2010
#define IDC_LISTBOX_VEHICLETYPE         2010
#define IDC_LIST_DIMENSION              2010
#define IDC_LISTBOX_ROUTELIST           2010
#define IDC_LISTBOX                     2010
#define IDC_LIST_LEFT                   2010
#define IDC_LIST_TOWOFFSTANDASSIGN      2010
#define IDC_TREE_TOWOFFSTANDASSIGN      2010
#define IDC_COMBO_INTERSECTRAIL         2011
#define IDC_LIST_QUEUELENGTH2           2011
#define IDC_LIST_PADAVAILABILITY        2011
#define IDC_LIST_RIGHT                  2011
#define IDC_LIST_APPROACH               2011
#define IDC_COMBO_GAP                   2012
#define IDC_COMBO_LEADAC                2012
#define IDC_COMBO_WEATHER               2013
#define IDC_LIST_COMPOSITE              2014
#define IDC_COMBO_TRAILAC               2014
#define IDC_COMBO_UNITS                 2015
#define IDC_EDIT_VARIATION              2016
#define IDC_RADIO_GAPYES                2016
#define IDC_LIST_INVENTORY              2017
#define IDD_DIALOG2                     2017
#define IDC_RADIO_GAPNO                 2017
#define IDD_DYNAMIC_RW_ASGN             2018
#define IDC_LIST_INTERSECTION           2018
#define IDD_DIALOG_DYNAMIC_RW_ASGN      2018
#define IDD_AS_SIMTIME_SETTING          2019
#define IDC_LIST_SEP                    2019
#define IDD_DIALOG_SIMTIME_SETTING      2019
#define IDD_RUNWAYASSIGNPAGE1           2020
#define IDD_RW_AVAILABLEMODE            2021
#define IDC_EDIT_VARIATIONS             2021
#define IDD_DIALOG_RUNWAYINVENTORY      2022
#define IDC_STATIC_RWPAIRBAR            2022
#define IDD_DIALOG_ATCSEPARATION        2023
#define IDC_STATIC_ATCSEPBAR            2023
#define IDR_TOOLBAR_ATCSEPARATION       2024
#define IDC_STATIC_INTERSECTION         2024
#define IDD_RUNWAYASSIGNPAGE2PRE        2025
#define IDR_TOOLBAR_RWPAIR              2026
#define IDC_WEATHERTOOL                 2026
#define IDR_TOOLBAR_WEATHER             2027
#define IDC_RWMODETOOLBAR               2027
#define IDR_TOOLBAR_NED_RW              2028
#define IDC_AS_SPIN1                    2029
#define IDC_SPIN2                       2030
#define IDC_AS_SPIN2                    2030
#define IDC_SPIN_ENDDAY                 2030
#define IDC_SPIN_AEEGAP                 2030
#define IDC_SPIN_LEADTIME               2030
#define IDR_TOOLBAR_RUNWAYASSIGN        2031
#define IDC_SPIN6                       2031
#define IDC_STATIC_DYNAMIC_RW_ASGN      2032
#define IDR_TOOLBAR_PAGEATCSEPDATA      2032
#define IDC_SPIN7                       2032
#define IDC_STATIC_FRAME_ATCSEPS        2033
#define IDD_DIALOG1                     2033
#define IDD_DIALOG_RUNWAYEXITDEF        2033
#define IDR_TOOLBAR_PAGATCSEPTYPE       2033
#define IDC_SPIN8                       2033
#define IDC_STATIC_FRAME_PROPERTIES     2034
#define IDD_DIALOG_SELECTFIX            2034
#define IDR_TOOLBAR_RWPROLLINGSPEED_RUNWAY 2034
#define IDC_STATIC_FRAME_SEP            2035
#define IDD_SIMSETTING_GENERAL          2035
#define IDR_TOOLBAR_RWROLLINGSPEED_TAXIWAY 2035
#define IDC_STATIC_FRAME_RWPAIR         2036
#define IDD_DIALOG_ATCSEPDATA           2036
#define IDC_SPIN18                      2036
#define IDC_STATIC_FRAME_UNITS          2037
#define IDD_DIALOG_ATCSEPDATATYPE       2037
#define IDC_SPIN9                       2037
#define IDC_STATIC_FRAME_VARIATION      2038
#define IDD_DIALOG3                     2038
#define IDD_DIALOG_ATCSEPITEM           2038
#define IDC_STATIC_FRAME_SECONDS        2039
#define IDC_STATIC_RAC_TOOLBAR          2040
#define IDD_DIALOG4                     2040
#define IDD_DIALOG_ATCRWPAIRS           2040
#define IDC_BUTTON1                     2041
#define IDC_SAVE                        2041
#define IDC_BUTTON_ADDFIX               2041
#define IDC_BUTTON_SAVE                 2041
#define IDR_CTX_MENURWASSIGN            2041
#define IDC_BUTTON_FLTTYPE              2041
#define IDC_BUTTON_FROM                 2041
#define IDC_PICK                        2041
#define IDC_BUTTON_PICK                 2041
#define IDC_BROWSE                      2041
#define IDC_BUTTON_LEFT                 2041
#define IDCSAVE                         2041
#define IDC_BUTTON_FLIGHTTYPE           2041
#define IDCANCLE                        2041
#define ID_BUTTON_APPLY                 2041
#define IDC_LIST2                       2042
#define IDC_LIST_SELECTEDFIXES          2042
#define IDB_WIZARD_MW                   2042
#define IDC_LIST_RWGAP                  2042
#define IDC_LIST_PERF_TAKEOFF           2042
#define IDC_LIST_DEP_CLIMB              2042
#define IDC_LIST_TAXIWAYDISTANCE        2042
#define IDC_LIST_ARWAYPOINT             2042
#define IDC_LIST_FLTTYPE                2042
#define IDC_LIST_PHASE_TYPE             2042
#define IDC_LIST_BASIS                  2042
#define IDC_LIST_TAXIWAY                2042
#define IDC_LIST_SERVICEREQUIREMENT     2042
#define IDC_LISTBOX_POOLS               2042
#define IDC_BROWSE2                     2042
#define IDC_DELETE                      2042
#define IDC_BUTTON_RIGHT                2042
#define IDC_BUTTON_OK                   2042
#define IDC_LIST_BOX_ATTRIBUTE          2042
#define IDC_PROPERTIRS_LIST             2042
#define IDC_LIST_PAD                    2042
#define IDC_LIST_EXITS                  2042
#define IDC_LIST_NODEBLOCK              2042
#define IDC_BUTTON_DELFIX               2043
#define IDB_BITMAP1                     2043
#define IDB_WIZARD_BANNER               2043
#define IDCSAVE2                        2043
#define IDC_BUTTON6                     2043
#define IDC_BUTTON_CANCEL               2043
#define IDC_DP_STARTTIME                2044
#define IDD_DIALOG_QUEUEMANAGEMENT      2044
#define IDC_DP_ENDTIME                  2045
#define IDD_EXCLUSIVE_USE_CRITERIA      2045
#define IDD_RUNWAYASSIGNPAGE2RAND       2046
#define IDD_DIALOG_INTERSECTIONBLOCKING 2047
#define IDD_DIALOG_PUSHBACKBLOCKING     2048
#define IDC_EDIT_STARTDAY               2049
#define IDD_DIALOG_SELECTDEPENDRW       2049
#define IDC_EDIT_ENDDAY                 2050
#define IDD_DIALOG_PERFOR_TAKEOFF       2050
#define IDC_SPIN_STARTDAY               2051
#define IDD_DIALOG_PERFOR_DEPARTURE_CLIMB 2051
#define IDC_EDIT_SCHPERCENT             2052
#define IDD_TAXI_INBOUND                2052
#define IDC_SPIN_SCHPERCENT             2053
#define IDD_DIALOG_RWROLLINGSPD         2053
#define IDC_EDIT_TIMESUBSET             2054
#define IDC_SPIN_TIMESUBSET             2055
#define IDC_EDIT_HEADWIND               2056
#define IDR_TOOLBAR_TAXIINBOUND         2056
#define IDC_SPIN_HEADWIND               2057
#define IDR_TOOLBAR_AIRLINEROUTINGPerformance 2057
#define IDR_TOOLBAR_AIRLINEROUTING      2057
#define IDC_EDIT_REPORT                 2058
#define IDD_NECRELATEDBASEDLG           2058
#define IDR_TOOLBAR_GENERAL             2058
#define IDC_SPIN_REPORT                 2059
#define IDD_DIALOG_GATETOWINGPARAM      2059
#define IDR_TOOLBAR_AIRROUTE_ARWAYPOINT 2059
#define IDC_COMBO_DELAYCHARGE           2060
#define IDD_DIALOG_DEPINTRAIL           2060
#define IDD_DIALOG_DEP_INTRAIL          2060
#define IDR_TOOLBAR_RUNWAYASSIGN1       2060
#define IDR_TOOLBAR_ADD_DEL             2060
#define IDR_TOOLBAR_RUNWAY_ADD_DEL      2060
#define IDC_COMBO_DEICINE               2061
#define IDC_COMBO_DECLINE               2061
#define IDD_DIALOG_AIRLINEROUTINGPERFORMANCE 2061
#define IDR_TOOLBAR_VEHICLESPECIFICATION 2061
#define IDR_TOOLBAR_EDIT                2062
#define IDC_RADIO_PREDEFINED            2063
#define IDD_DIALOG_TAXISPEEDMODIFIER    2063
#define IDR_TOOLBAR_PRIORITY_OCCUPIED   2063
#define IDC_RADIO_RANDOM                2064
#define IDD_DIALOG5                     2064
#define IDD_DIALOG_TAXIWAYOPERATIONALDESIGNATION 2064
#define IDR_TOOLBAR_FLTREL              2064
#define IDC_TREE_RANDASSIGN             2065
#define IDD_DIALOG6                     2065
#define IDD_DIALOG_RUNWAYEXITPROB       2065
#define IDR_TOOLBAR_DEPSLOT             2065
#define IDC_EDIT_FREEDISTANCE           2066
#define IDD_DIALOG_FLTSCHEDULE_SETTING  2066
#define IDC_SPIN_FREEDISTANCE           2067
#define IDC_EDIT_DISTANCE               2068
#define IDD_DIALOG_ARWAYPOINTDEFINE     2068
#define IDC_SPIN1                       2069
#define IDC_TREE_ATCDATA                2070
#define IDC_SPIN_MAXSPEED               2070
#define IDD_DIALOG_AIRCRAFTCLASSIFICATION 2070
#define IDC_SPIN_MIN_TIME               2070
#define IDC_SPIN10                      2070
#define IDC_STATIC_TOOLBAR              2071
#define IDC_SPIN_MINHEIGHT              2071
#define IDD_TAKEOFFRUNWAYASSIGN         2071
#define IDC_SPIN13                      2071
#define IDC_STATIC_BANNER               2072
#define IDC_SPIN_MAXHEIGHT              2072
#define IDD_TIMERANGE                   2072
#define IDC_STATIC_TOOLBAR2             2072
#define IDC_SPIN14                      2072
#define IDC_STATIC_BANNAR               2073
#define IDD_SELECTAIRROUTE              2073
#define IDC_TREE_DATA                   2074
#define IDD_NECRELATEDBASEDLG1          2075
#define IDD_ARRIVALINIT                 2075
#define IDR_HTML_DLGFLIGHTTYPERESTRICTIONS 2076
#define IDC_COMBO_UNIT                  2077
#define IDD_DIALOG_SECTOR               2077
#define IDR_MENU1                       2078
#define IDC_SPIN_VARIATION              2079
#define IDD_DIALOG7                     2079
#define IDD_LANDIINGRUNWAYEXIT          2079
#define IDR_CTX_MENU_STRATERY_TIMERANGE 2079
#define IDR_CTX_MENU_STRATEGY_TIMERANGE 2079
#define IDC_LIST_ALLRUNWAYS             2080
#define IDC_BUTTON_ADDRUNWAYS           2081
#define IDD_DIALOG8                     2081
#define IDC_BUTTON_DELRUNWAYS           2082
#define IDD_GROUNDROUTE                 2082
#define IDC_LIST_SELECTEDRUNWAYS        2083
#define IDC_CHECK_GAP                   2084
#define IDD_RUNWAYTAKEOFFPOSITION       2084
#define IDC_CHECK_SYNC                  2085
#define IDR_MENU_RUNWAYTAKEOFFPOSITION  2085
#define IDD_STANDBUFFER                 2086
#define IDR_MENU_SIDESTEPSPECIFICATION  2086
#define IDC_EDIT_ARRGAP                 2087
#define IDD_DIALOG_SELECTALTOBJECT      2087
#define IDR_MENU_CONFLICTRESOLUTION     2087
#define IDD_DIALOG_SELECTALT            2087
#define IDD_TAKEOFFQUEUE                2088
#define IDR_MENU_COMMON                 2088
#define IDC_EDIT_DEPGAP                 2089
#define IDD_DIALOG_APPROCHSEPARATION    2089
#define IDR_MENU_ADD_EDIT_DEL           2089
#define IDR_MENU_ADD_DEL_EDIT           2089
#define IDC_SPIN_DEPGAP                 2090
#define IDD_DIALOG9                     2090
#define IDD_TAKEOFFSEQUENCE             2090
#define IDC_STATIC_ARRAGP               2091
#define IDD_DIALOG_IN_TRAIL_SEPARATION  2091
#define IDC_STATIC_DEPGAP               2092
#define IDD_DIALOG_ITINERANTTRAFFIC     2092
#define IDC_EDIT_CANOK                  2093
#define IDD_DIALOG_ITINERANTTRAFFIC_DEFINE 2093
#define IDC_EDIT2                       2094
#define IDC_EDIT_IFR                    2094
#define IDC_EDIT_RUNWAY                 2094
#define IDC_EDIT_LEADTIME               2094
#define IDC_EDIT_TIMEDIF_FLIGHTPLAN     2094
#define IDC_EDIT_FLTTYPE                2094
#define IDD_DIALOG_TAXIWAY_WEIGHT_CONSTRAINT 2094
#define IDD_DIALOG_TAXIWAY_CONSTRAINT   2094
#define IDC_EDIT_TIMEDIF_RUNWAY         2095
#define IDD_DIALOG10                    2095
#define IDD_DIALOG_SIDASSIGNMENT        2095
#define IDC_EDIT_TAXIWAY                2096
#define IDC_EDIT_DISDIFF_FLIGHTPLAN     2096
#define IDC_EDIT1                       2097
#define IDC_EDIT_ROLLINGSPD             2097
#define IDC_EDIT_SPEEDFACTOR            2097
#define IDC_EDIT_WEIGHT                 2097
#define IDC_EDIT_STARTNUMBER            2097
#define IDC_EDIT_MINSPEED               2097
#define IDC_EDIT_DISDIFF_RUNWAY         2097
#define IDC_EDIT_ENDNUMBER              2098
#define IDC_EDIT_MAXSPEED               2098
#define IDC_EDIT3                       2098
#define IDC_EDIT_MIN_TIME               2098
#define IDC_EDIT_TIMEDIF_FLIGHTPLAN2    2098
#define IDD_DIALOG_WEATHERIMPACT        2098
#define IDC_SPIN_ROLLINGSPD             2099
#define IDC_EDIT_MINHEIGHT              2099
#define IDC_EDIT_TIMEDIF_RUNWAY2        2099
#define IDC_EDIT_TOP1                   2099
#define IDD_DIALOG_STARASSIGNMENT       2099
#define IDC_EDIT_TOSTAND                2099
#define IDC_EDIT10                      2099
#define IDC_STATIC_TOOLBAR_RUNWAY       2100
#define IDC_EDIT_MINTIME                2100
#define IDC_EDIT_HEIGHT                 2100
#define IDC_EDIT_DISDIFF_FLIGHTPLAN2    2100
#define IDC_EDIT_TOP2                   2100
#define IDC_EDIT_TOTEMPORARYPARKING     2100
#define IDC_EDIT11                      2100
#define IDC_STATIC_TOOLBAE_TAXIWAY      2101
#define IDC_EDIT_MAXTIME                2101
#define IDC_EDIT_DISDIFF_RUNWAY2        2101
#define IDD_DIALOG_TBTSAMERUNWAY        2101
#define IDC_GROUPBOX_NECRELATED         2102
#define IDC_EDIT_FIXEDTIME              2102
#define IDD_DIALOG_TBTINTERSECT         2102
#define IDC_SPIN_SPEEDFACTOR            2103
#define IDD_DIALOG_TBLSAMERUNWAY        2103
#define IDD_DIALOG_TBLINTERSECT         2104
#define IDC_BUTTON3                     2105
#define IDC_BUTTON_MOVE_FROM_TREE       2105
#define IDC_BUTTON_DELETE               2105
#define IDC_BUTTON_EXIT                 2105
#define IDC_BUTTON_SAVEAS               2105
#define IDC_SPIN_TAXIWAY                2106
#define IDD_DIALOG_CTRLINTERVENTIONSPEC 2106
#define IDC_SPIN_RUNWAY                 2107
#define IDD_DIALOG1_INBOUNDROUTEASSIGN  2107
#define IDD_DIALOG_INBOUNDROUTEASSIGN   2107
#define IDC_SPIN_WEIGHT                 2108
#define IDD_DIALOG_RUNWAYEXITANDSTANDFAMILYSELECT 2108
#define IDC_STATIC_AREA                 2110
#define IDC_STATIC1                     2111
#define IDC_STATIC2                     2112
#define IDC_STATIC3                     2113
#define IDD_DIALOG11                    2113
#define IDD_DIALOG1_LAHSO               2113
#define IDC_RADIO_USERDEF               2114
#define IDD_SELECTTAKEOFFPOSITION       2114
#define IDC_RADIO_AUTODEF               2115
#define IDD_DIALOG_WAYPOINTANDSTANDFAMILY 2115
#define IDC_RADIO_FIXEDTIME             2116
#define IDD_DIALOG12                    2116
#define IDD_DIALOG_SELECTINBOUNDROUTEITEM 2116
#define IDC_RADIO_PATHBASED             2117
#define IDD_DIALOG13                    2117
#define IDD_DIALOG_OUTBOUNDROUTEASSIGN  2117
#define IDC_SPIN3                       2118
#define IDD_DIALOG14                    2118
#define IDD_DIALOG_SELSTANDANDRUNWAYEXIT 2118
#define IDC_SPIN4                       2119
#define IDD_DIALOG15                    2119
#define IDD_DIALOG_VEHICLESPECIFICATION 2119
#define IDC_SPIN5                       2120
#define IDD_DIALOG_DIRECTROUTINGSELECTWAYPOINT 2120
#define IDC_TREE_SELECTEDFIXES          2121
#define IDD_DIALOG_CONFLICTRESOLUTION   2121
#define IDC_COMBO_TYPE                  2122
#define IDD_DIALOG_CONFLICTSELECTTAXIWAY 2122
#define IDC_COMBO2                      2123
#define IDC_COMBO_RUNWAY                2123
#define IDC_COMBO_PRIORITYTWO           2123
#define IDD_DIALOG_PUSHBACKCLEARANCECRITERIA 2123
#define IDC_COMBO_INTERSECTIONTAXIWAY2  2123
#define IDC_STATIC_WAYPOINTTOOLBAR      2124
#define IDC_STATIC_TOOLBARWAYPOINT      2124
#define IDD_DIALOG_OCCUPIEDASSIGNEDSTANDACTION 2124
#define IDD_DIALOG_AIRROUTEDEFINE       2125
#define IDC_STATIC_TOOLBARAIRROUTE      2126
#define IDD_DIALOG_OCCUPIEDSELECTSTAND  2126
#define IDC_LISTBOX_AIRROUTE            2127
#define IDD_DIALOG_TAXIWAY_FLIGHT_TYPE_RESTRICTION 2127
#define IDC_COMBO_WAYPOINT              2128
#define IDD_DIALOG_TEMP                 2128
#define IDD_DIALOG_TEMPORARY_PARKING_CRITERIA 2128
#define IDC_RADIO_MINSPEEDNOLIMIT       2129
#define IDD_DIALOG_TAXIWAYOPERATIONALDESIGNATION1 2129
#define IDC_RADIO_MINSPEEDDEFINE        2130
#define IDD_LANDIINGRUNWAYEXIT1         2130
#define IDD_SIDESTEPCRITERIA            2130
#define IDC_RADIO_MAXSPEEDNOLIMIT       2131
#define IDD_DIALOG_DIRECTROUTING        2131
#define IDC_RADIO_MAXSPEEDDEFINE        2132
#define IDD_DIALOG_OCCUPIEDSELECTTEMPORARYPARKING 2132
#define IDC_RADIO_MINHEIGHTNOLIMIT      2133
#define IDC_RADIO_MINHEIGHTDEFINE       2134
#define IDC_RADIO_MAXHEIGHTNOLIMIT      2135
#define IDD_DIALOG16                    2135
#define IDD_DIALOG_OCCUPIEDSELECTINTERSECTION 2135
#define IDC_RADIO_MAXHEIGHTDEFINE       2136
#define IDD_DIALOG_OCCUPIEDASSIGNEDSTAND 2136
#define IDC_SPIN_MINSPEED               2137
#define IDC_COMBO1                      2138
#define IDC_COMBO_RUNWAYMARK            2138
#define IDC_COMBO_ASSIGNSTRATEGY        2138
#define IDC_COMBO_STARTDAY              2138
#define IDC_COMBO_MAX_AIRCRAFT          2138
#define IDC_COMBO_CA                    2138
#define IDC_COMBO_CATEGORY_TYPE         2138
#define IDC_COMBO_PRIORITYONE           2138
#define IDC_COMBO_AIRCRAFT_CLASSIFICATION 2138
#define IDC_COMBO_INTERSECTIONTAXIWAY1  2138
#define IDD_DIALOG_OCCUPIEDDELAYTIME    2138
#define IDC_COMBO_AIRCRAFT              2138
#define IDC_COMBOHEADINGCHOICE          2138
#define IDC_TREE_FLTTIME                2139
#define IDC_COMBO_ENDDAY                2139
#define IDC_COMBO_CLASSIFICATION_BASIS  2139
#define IDC_COMBO3                      2139
#define IDD_DIALOG_TOWINGROUTE          2139
#define IDC_DATETIMEPICKER_STARTTIME    2140
#define IDC_COMBO4                      2140
#define IDD_DIALOG_TOWINGROUTE_FROMANDTO 2140
#define IDC_DATETIMEPICKER_ENDTIME      2141
#define IDC_TREE1                       2141
#define IDC_TREE_AIRROUTES              2141
#define IDC_TREE_ROUTE                  2141
#define IDC_TREE                        2141
#define IDC_TREE_RUNWAYEXIT             2141
#define IDC_TREE_GROUNDROUTES           2141
#define IDC_TREE_                       2141
#define IDC_TREE_FLTTIMERANGE           2141
#define IDC_TREE_ALTOBJECT              2141
#define IDC_TREE_RUNWAYINTERSECTION     2141
#define IDC_TREE_TAKEOFFSEQUENCE        2141
#define IDC_TREE_SIDASSIGNMENT          2141
#define IDC_TREE_LANDINGRUNWAY          2141
#define IDC_TREE_GROUNDROUTEITEM        2141
#define IDC_TREE_CONFLICTRESOLUTION     2141
#define IDC_TREE_CONDITION              2141
#define IDC_COMBO_TOSTAND               2141
#define IDD_DIALOG17                    2141
#define IDD_DIALOG_TOWINGROUTESTANDFAMILYANDTEMPORARYPARKING 2141
#define IDC_TREE_INTERRUPT              2141
#define IDC_TREE_CRITERIA               2141
#define IDC_COMBO5                      2142
#define IDD_DIALOG_                     2142
#define IDD_DIALOG_SERVICEREQUIREMENT   2142
#define IDC_COMBO6                      2143
#define IDD_DIALOG_VEHICLEPOOLSANDDEPLOYMENT 2143
#define IDD_DIALOG_STANDFAMILY          2144
#define IDC_RADIO3                      2145
#define IDD_DIALOG_FLIGHTTYPE_DIMENSIONS 2145
#define IDC_RADIO4                      2146
#define IDC_TREE_ROUTE_ITEM             2147
#define IDC_RADIO_TOP2                  2147
#define IDD_DIALOG_FLIGHT_RELATIVE      2147
#define IDD_DIALOG_FLIGHTTYPE_RELATIVE  2147
#define IDC_TREE_ROUTE_TREE             2148
#define IDC_BUTTON2                     2149
#define IDC_BUTTON_MOVE_TO_TREE         2149
#define IDC_BUTTON_ADD                  2149
#define IDC_BUTTON_ENTRY                2149
#define IDC_BUTTON_DELAYTIME            2149
#define IDC_BUTTON_TO                   2149
#define IDC_BUTTON_SLS                  2149
#define IDD_DIALOG18                    2149
#define IDD_DIALOG_VEHICLEROUTES        2149
#define IDC_BUTTON_INTERMEDIATESTANDS   2149
#define IDC_VIEW_SCHEDUAL               2149
#define IDC_BUTTON_TRIAL_SEPARATION_CANCEL 2149
#define IDC_UPDATE_SCHEDULE             2149
#define IDC_BUTTON_LOAD                 2149
#define IDC_BTN_WS_ADJCONS              2149
#define IDC_TREE_RUNWAYTAXIWAY          2150
#define IDC_BUTTON_INTERSECTION         2150
#define IDD_DIALOG_DEPARTURESLOT        2150
#define IDC_TREE_RUNWAY                 2151
#define IDC_BUTTON_STAND                2151
#define IDC_CHECK_ELIGIBLE              2152
#define IDC_BUTTON7                     2152
#define IDC_BUTTON_TEMPORARYPARKING     2152
#define IDD_DIALOG19                    2152
#define IDD_DIALOG_FLIGHTTYPE_RESTRICTIONS 2152
#define IDD_DIALOG_WAYPOINT_IMPORT      2153
#define IDC_EDIT_REMAINING              2153
#define IDC_SPIN_REMAINING              2154
#define IDR_TOOLBAR_IPORT               2154
#define IDC_LIST_STANDBUFFER            2155
#define IDR_TOOLBAR_DIRCONS             2155
#define IDC_TREE2                       2156
#define IDC_TREE_QUEUENODES             2156
#define IDC_TREE_STANDFAMILY            2156
#define IDR_TOOLBAR_APPROACH            2156
#define IDC_COMBO_BASIS                 2157
#define IDC_STATIC_BASIS                2158
#define IDD_DIALOG_DIRECTIONALITYCONSTRAINTS 2158
#define IDC_EDIT_LEADDIS_FROM_THRESHOLD 2159
#define IDD_DIALOG_AIRCRAFS             2159
#define IDD_DIALOG_AIRCRAFT_ALIAS       2159
#define IDC_STATIC_LEADDIS_FROM_THRESHOLD 2160
#define IDS_STRINGAIRCRAFTALIAS         2160
#define IDI_ICON_TOWTRUCK               2161
#define IDC_STATIC_TIMEDIF_FLIGHTPLAN   2162
#define IDI_ICON_STAIRS                 2162
#define IDC_STATIC_TIMEDIF_RUNWAY       2163
#define IDI_ICON_STAFFCAR               2163
#define IDC_STATIC_DISDIFF_FLIGHTPLAN   2164
#define IDI_ICON_PAXBUSC                2164
#define IDC_STATIC_DISDIFF_RUNWAY       2165
#define IDI_ICON_PAXBUSB                2165
#define IDC_TREE_APPROCH                2166
#define IDI_ICON_PAXBUSA                2166
#define IDC_TREE_LAHSO                  2167
#define IDI_ICON_OTHERS                 2167
#define IDC_SPIN_MIN_DISTANCE           2168
#define IDI_ICON_MAINTENANCE            2168
#define IDC_EDIT_MIN_DISTANCE           2169
#define IDI_ICON9                       2169
#define IDI_ICON_LIFTS                  2169
#define IDC_DATETIMEPICKER_FROM         2170
#define IDI_ICON_FUELING                2170
#define IDC_DATETIMEPICKER2             2171
#define IDC_DATETIMEPICKER_TO           2171
#define IDI_ICON_DEICINGTRUCK           2171
#define IDC_EDIT_NAME                   2172
#define IDI_ICON_CREWBUS                2172
#define IDC_COMBO_ENTRY                 2173
#define IDI_ICON_CONVEYORS              2173
#define IDC_COMBO_EXIT                  2174
#define IDI_ICON_CATERINGTRUCK          2174
#define IDC_COMBO_DISTRIBUTION          2175
#define IDI_ICON_CARGOULDCARTS          2175
#define IDC_STATIC_TREE                 2176
#define IDI_ICON_CARGOTUGS              2176
#define IDC_STATIC_LIST                 2177
#define IDI_ICON_BAGGAGETUGS            2177
#define IDC_TREE_TAKEOFF                2178
#define IDI_ICON_BAGGAGECARS            2178
#define IDC_STATIC_CLEAREDTOPOSITION    2179
#define IDD_DIALOG_TOWOFFSTANDASSIGNMENT 2179
#define IDC_RADIO1                      2180
#define IDD_DIALOG_NEWEDITTOWOFFSTANDASSIGN 2180
#define IDC_RADIO2                      2181
#define IDD_DIALOG_SELECTINTERMEDIATESTANDS 2181
#define IDC_SCROLLBAR1                  2182
#define IDC_RADIO5                      2182
#define IDB_BITMAP_UNITSETTING          2182
#define IDC_EDIT6                       2183
#define IDC_EDIT_TOP3                   2183
#define IDC_RADIO6                      2183
#define IDD_DIALOG_UNITMANAGER_SETTING  2183
#define IDC_RADIO_TOP1                  2184
#define IDD_DIALOG20                    2184
#define IDD_DIALOG_STRETCHOPTION        2184
#define IDC_SPIN_TOP1                   2185
#define IDC_SPIN_TOP2                   2186
#define IDD_DIALOG_ITINERANTFLIGHT_SCHEDULE 2186
#define IDC_SPIN_TOP3                   2187
#define IDC_STATIC_TOP1                 2188
#define IDD_DIALOG_ITINERANTFLIGHT_SCHEDULEDEFINE 2188
#define IDC_STATIC_TOP2                 2189
#define IDD_DIALOG_ARRIVALETAOFFSET     2189
#define IDC_STATIC_TOP3                 2190
#define IDD_DIALOG_APPROCHASEPARATION_CRITERIA 2190
#define IDC_STATIC_TOP4                 2191
#define IDD_DIALOG_APPROACHSEPARATIONITEM 2191
#define IDD_DIALOG_TRAIL_SEPARATION     2192
#define IDR_TOOLBAR1                    2193
#define IDR_TOOLBAR_SEPARATION          2193
#define IDR_HTML_DLGCONTROLLERSOCTER    2194
#define IDR_TOOLBAR_TRIALSEPARATION     2195
#define IDD_DIALOG_ENGINEPARAMETERS     2196
#define IDD_DIALOG21                    2197
#define IDD_DIALOG_TRAIL_SEPARATION_SUB 2197
#define IDD_DIALOG_SELECT_TWO_RUNWAY    2198
#define IDC_STATIC_WEATHERCONDITION     2199
#define IDD_DIALOG_TAKEOFFCLEARANCECRITERIA 2199
#define IDC_STATIC_WEATHERIMPACTS       2200
#define IDD_DIALOG_IN_TRAIL_SEPARATIONEX 2200
#define IDC_TREE_WEATHERCONDITION       2201
#define IDD_DIALOG_SECTOR_SELECT        2201
#define IDC_STATIC_LANDINGRUNWAY        2202
#define IDR_TOOLBAR_INTRAIL             2202
#define IDC_STATIC_STARASSIGNMENT       2203
#define IDR_MENU_PHASE                  2203
#define IDC_STATIC_TIME                 2204
#define IDD_DIALOG_PADCONDITION         2204
#define IDC_STATIC_FILGHTTYPE           2205
#define IDR_TOOLBAR_PAD_ADD_DEL         2205
#define IDR_TOOLBAR_FLIGHT_TYPE         2206
#define IDC_STATIC_TIMEFRM              2207
#define IDD_DIALOG_DEICEPADROUTE        2207
#define IDD_DIALOG_DEICEROUTE           2207
#define IDC_STATIC_TIMETO               2208
#define IDR_STAND_TOOLBAR               2208
#define IDR_DEICEPAD_TOOLBAR            2209
#define IDC_STATIC_SIDTOOLBAR           2210
#define IDR_MENU_BACKTRACK              2210
#define IDC_STATIC_GROUP                2211
#define IDD_DIALOG_INTERVENTION_SECTOR  2211
#define IDC_EDIT4                       2212
#define IDD_DIALOG_DEICEING_QUEUE       2212
#define IDC_EDIT5                       2213
#define IDR_DEICEQUEUE_TOOLBAR          2213
#define IDR_ROUTEPATH_TOOLBAR           2214
#define IDC_STATIC_PRIORITYONE          2215
#define IDD_DIALOG_SELECTSECTOR         2215
#define IDC_STATIC_PRIORITYTWO          2216
#define IDD_DIALOG_ACTYPESELECTION      2216
#define IDC_STATIC_PRIORITYTHREE        2217
#define IDD_DIALOG_SECTORLIMITATION     2217
#define IDC_COMBO__PRIORITYTHREE        2218
#define IDR_TOOLBAR_STANDBUFFER         2218
#define IDC_STATIC_OPERATION_TOOLTIPS   2219
#define IDR_MENU2                       2219
#define IDR_TOOLBAR_VEHICULARMOVEMENTALLOWED 2219
#define IDC_STATIC_LEAD_DISTANCE        2220
#define IDD_DIALOG_VEHICULARMOVEMENT    2220
#define IDC_EDIT_LEAD_DISTANCE          2221
#define IDD_STANDCRITERIAASSIGNMENT     2221
#define IDC_STATIC_                     2222
#define IDC_STATIC_UNIT                 2222
#define IDC_STATIC_LEFTGROUPBOX         2222
#define IDC_STATIC_SECTOR               2222
#define IDR_STANDCRITERIA_TOOLBAR       2222
#define IDC_RADIO_SHORTESTPATH          2223
#define IDR_MENU_STAND                  2223
#define IDC_RADIO_TIMESHORTEST          2224
#define IDR_MENU4                       2224
#define IDC_RADIO_PREFERREDROUTE        2225
#define IDR_MENU_FLIGHTTYPE             2225
#define IDC_STATIC_RUNWAYEXITANDSTANDFAMILY 2226
#define IDR_TOOLBAR_RUNWAYPOINT_ADD_DEL 2226
#define IDC_STATIC_ROUTE                2227
#define IDR_TOOLBAR_ADD_DEL_EDIT1       2227
#define IDR_TOOLBAR_ADD_DEL_EDIT_RUNWAYASSIGN 2227
#define IDD_DIALOG_INTERRUPT_TIMES      2227
#define IDC_EDIT_RUNWAYEXIT             2228
#define IDD_DIALOG_SHORTLINE_SEL        2228
#define IDC_EDIT_STANDFAMILY            2229
#define IDR_TOOLBAR_HOLDSHORT_LINE      2229
#define IDC_TREE3                       2230
#define IDC_TREE_INTERSECTIONS          2230
#define IDC_STATIC_GROUNDROUTE          2231
#define IDD_DIALOG_SURFACE_CONDITION    2231
#define IDC_STATIC_GROUNDROUTEITEM      2232
#define IDR_TOOLBAR_CONDITION           2232
#define IDR_TOOLBAR_WAVECROSSRUNWAY     2233
#define IDD_DIALOG_WAVECROSSRUNWAYSPECIFICATION 2234
#define IDD_DIALOG_SURFACEINITAL        2235
#define IDD_DIALOG_WEATHER_SCRIPT       2236
#define IDR_TOOLBAR_WEATHERSCRIPT       2237
#define IDC_STATIC_ROUTEASSIGNMENTCATEGORY 2238
#define IDC_STATIC_ROUTEASSIGNMENT      2239
#define IDR_TOOLBAR_SURFACE             2239
#define IDR_TOOLBAR_AIRSURFACE          2239
#define IDC_LIST_TAKEOFFQUEUE           2240
#define IDR_TOOLBAR_WAVECROSSRUNWAY1    2240
#define IDR_TOOLBAR_PUSHBACKANDTOWOPERATION 2240
#define IDC_TREE_TAKEOFFPOSI            2241
#define IDR_MENU_DEPSTAND               2241
#define IDC_TREE_FLTRUNWAY              2242
#define IDR_MENU3                       2242
#define IDR_MENU_DEICESTAND             2242
#define IDC_LIST_GSE                    2242
#define IDC_TREE_RUNWAYDATA             2243
#define IDD_DIALOG_PUSHBACKANDTOWOPERATION 2243
#define IDC_STATIC_SIDESTEPSPECI        2244
#define IDR_MENU_PRIORITY               2244
#define IDC_STATIC_TAKEOFFQUEUES        2245
#define IDD_DIALOG_ALTOBJECT            2245
#define IDR_CTX_MENU_EXITSTRATEGY       2245
#define IDC_STATIC_TAKEOFFQUEUENODE     2246
#define IDR_CTX_MENU_STRATEGYPRIORITY   2246
#define IDR_CTX_MENU_STRATEGY_PRIORITY  2246
#define IDD_DIALOG_EXITS_SEL            2246
#define IDC_BUTTON4                     2247
#define IDC_BUTTON_TIMEWINDOW           2247
#define IDC_BUTTON_ARRTIMEWINDOW        2247
#define IDR_MENU5                       2247
#define IDR_MENU_FLTTYPE                2247
#define IDC_EDIT_ENTRY                  2248
#define IDD_DIALOG_TIME_PICKER          2248
#define IDC_EDIT_EXIT                   2249
#define IDR_TOOLBAR_ROUTE_PRIORITY      2249
#define IDC_EDIT_TIMEWINDOW             2250
#define IDC_EDIT_ARRTIMEWINDOW          2250
#define IDR_MENU_TAKEOFFRWYASSIGN       2250
#define IDR_TOOLBAR_HOLDSHORT_LINE1     2250
#define IDC_TREE_WAYPOINT_STANDFAMILY   2251
#define IDC_TREE_WAYPOINTANDSTANDFAMILY 2251
#define IDR_MENU_TAKEOFFFLTTIME         2251
#define IDR_TOOLBAR_WINGSPAN_ADJCONS    2251
#define IDC_EDIT_ALTOBJNAME             2252
#define IDR_MENU_STANDPOPMENU           2252
#define IDC_TREE_ALTOBJLIST             2253
#define IDR_MENU_FLTTYPEPOPMENU         2253
#define IDC_EDIT_NUMBEROFFLIGHTS        2254
#define IDR_MENU_TIMEWINPOPMENU         2254
#define IDC_STATIC_RIGHTGROUPBOX        2255
#define IDR_MENU_RUNWAYPOPMENU          2255
#define IDC_STATIC_PHASE                2256
#define IDR_MENU_TAKEOFFPOSPOPMENU      2256
#define IDC_STATIC_CLASSIFICATION       2257
#define IDD_DIALOG_WINGSPAN_ADJCONS     2257
#define IDR_TOOLBAR_ASSIGNEDSTAND_LIST  2257
#define IDC_LIST_DIRECTROUTING          2258
#define IDC_STATIC_FRAME                2258
#define IDR_TOOLBAR_ASSIGNEDSTAND_ORDER 2258
#define IDC_TREE_WAYPOINTSTART          2259
#define IDR_TOOLBAR_ASSIGNEDSTAND_ORDER1 2259
#define IDC_TREE_WAYPOINTSTART2         2260
#define IDC_TREE_WAYPOINTMAX            2260
#define IDC_STATIC_INCLUDE              2260
#define IDD_DIALOG_OCCUPIEDASSIGNEDSTAND_SELECT 2260
#define IDC_TREE_WAYPOINTEND            2261
#define IDC_STATIC4                     2261
#define IDC_STATIC5                     2262
#define IDC_STATIC_CONFLICTRESOLUTION   2263
#define IDC_TREE_CONFLICTSELECTTAXIWAY  2264
#define IDR_MENU_ADD_FLIGHTTYPE         2264
#define IDD_DIALOG_DE_ICINGANDANTI_ICINGSTRATEGIES 2265
#define IDR_MENU_ADD_TIMEWINDOW         2265
#define IDD_DIALOG_SELSTAND_DEICEPAD    2266
#define IDC_STATIC_FORANY               2267
#define IDD_DIALOG_OCCUPIEDASSIGNEDSTAND_ORDER 2267
#define IDD_DIALOG_DEICEPADFAMILY       2268
#define IDC_STATIC_ALLINCLUDE           2269
#define IDD_DIALOG_SELECTTOWROUTEITEM   2269
#define IDC_STATIC_VALUEINCLUDE         2270
#define IDD_DIALOG_INTERSECTION_SELECT  2270
#define IDC_STATIC_TOOLBAR_RECT         2271
#define IDR_POPUPMENU_INTERSECTION      2271
#define IDC_STATIC_FLTTYPE              2272
#define IDR_POPMENU_DEL_INTERSECTION    2272
#define IDR_POPUPMENU_DEL_INTERSECTION  2272
#define IDC_EDIT_TODELAYTIME            2273
#define IDC_EDIT_INTERSECTION           2274
#define IDC_EDIT_TOINTERSECTION         2274
#define IDR_MENU_FLIGHTSTYPEMANAGEMENT  2274
#define IDC_COMBO_TODELAYTIME           2275
#define IDR_MENU_TIMENRANGE             2275
#define IDC_COMBO_TOINTERSECTION        2276
#define IDR_MENU_TAKEOFFFLIGHTSPOSITION 2276
#define IDC_COMBO_TOTEMPORARYPARKING    2277
#define IDD_DIALOG_TRAINFLIGHTSMANAGEMENT 2277
#define IDC_COMBO_TODYNAMICALSTAND      2278
#define IDD_DIALOG22                    2278
#define IDD_DIALOG_SELECTTAXIWAY_SEGMENT 2278
#define IDC_STATIC_PRIORITY             2279
#define IDC_TREE_OCCUPIEDSELECTSTAND    2280
#define IDC_TREE_OCCUPIEDSELECTTEMPORARYPARKING 2281
#define IDC_COMBO_INTERSECTIONINDEX     2283
#define IDC_STATIC_LARGE                2284
#define IDC_STATIC_SMALL                2285
#define IDC_STATIC_INTERSECTIONS        2286
#define IDC_STATIC_PROPERTIES           2287
#define IDC_STATIC_REMAINING            2288
#define IDD_DIALOG_SELECTDEICEPADS      2289
#define IDC_STATIC_DATA                 2290
#define IDC_STATIC_M                    2291
#define IDC_STATIC_TODELAYTIME          2292
#define IDC_STATIC_TOINTERSECTION       2293
#define IDC_STATIC_TOSTAND              2294
#define IDC_STATIC_TOTEMPORARYPARKING   2295
#define IDC_STATIC_TODYNAMICAL          2296
#define IDC_STATIC_TODYNAMICALSTAND     2296
#define IDC_STATIC_TODELAYTIME2         2297
#define IDC_STATIC_TOINTERSECTION2      2298
#define IDC_STATIC_STAND2               2299
#define IDC_STATIC_TOTEMPORARYPARKING2  2300
#define IDC_STATIC_STRATEGY_TITLE       2301
#define IDC_TREE_STANDBUFFER            2302
#define IDC_STATIC_PRIORITY1            2303
#define IDC_STATIC_PRIORITY2            2304
#define IDC_STATIC_PRIORITY3            2305
#define IDC_STATIC_PRIORITY4            2306
#define IDC_STATIC_PRIORITY5            2307
#define IDC_LIST_OCCUPIED_PRIORITY      2308
#define IDC_EDIT_DELAYTIME              2309
#define IDC_STATIC_TOWINGROUTE          2310
#define IDC_STATIC_TEXT                 2310
#define IDC_TREE_TOWINGROUTE            2311
#define IDC_EDIT_FROM                   2312
#define IDC_EDIT_TO                     2313
#define IDC_TREE_STANDFAMILYANDTEMPORARYPARKING 2314
#define IDC_LIST_FLIGHTTYPE             2315
#define IDD_DLGRELEASEPOINTSELECTION    2316
#define IDC_STATIC_VEHICLETYPE          2317
#define IDD_TAXISPEED_CONSTRAINT        2317
#define IDC_STATIC_POOLS                2318
#define IDD_DIALOG_TAXIWAYFAMILY        2318
#define IDC_GROUPBOX_POOLS              2319
#define IDC_STATIC_ATTRIBUTES           2320
#define IDC_GROUPBOX_ATTRIBUTES         2321
#define IDC_TREE_ATTRIBUTES             2322
#define IDC_FLIGHT2D1                   2323
#define IDC_PLACEHOLDER                 2324
#define IDC_LIST_RELATIVE               2325
#define IDC_GROUPBOX_ROUTE              2326
#define IDC_EDIT                        2326
#define IDC_STATIC_FIRST                2327
#define IDC_GROUPBOX_VEHICLEROUTE       2327
#define IDC_STATIC_SECOND               2328
#define IDC_STATIC_RIGHTINCLUDE         2329
#define IDC_STATIC_FIRST_HEAD           2330
#define IDC_STATIC_SECONDE_HEAD         2331
#define IDC_STATIC_SECOND_HEAD          2331
#define IDC_STATIC_IMPORT               2332
#define IDD_DLGINTERSECTIONNODEBLOCK    2334
#define IDD_DIALOG_BOUNDROUTEASSIGN     2335
#define IDD_DIALOG_SELSTANDANDRUNWAYEXIT1 2336
#define IDD_DIALOG_SEL_ORIGDEST         2336
#define IDD_DIALOG_TRAINFLIGHTSPEC      2337
#define IDC_STATIC_ZS                   2340
#define IDC_STATIC_FM                   2343
#define ID_SAVE                         2344
#define IDC_STATIC_LEFT                 2346
#define IDC_STATIC_RIGHT                2347
#define IDC_GROUPBOX_TAXIWAY            2348
#define IDC_GROUPBOX_CONSTRAINT         2349
#define IDC_STATIC_TAXI                 2350
#define IDC_STATIC_GRIDDEF              2351
#define IDC_STATIC_DIMDEF               2352
#define IDC_STATIC_FLTDEF               2353
#define IDC_SLIDER_EXTX                 2354
#define IDC_SLIDER_EXTY                 2355
#define IDC_STATIC_GROUPBOX             2355
#define IDC_EDIT_FLIGHTTYPE             2356
#define IDC_EDIT_DEPLANEMENTTIME        2357
#define IDC_EDIT_ENPLANEMENTTIME        2358
#define IDC_EDIT_TOWOFFCRITERIA         2359
#define IDC_EDIT_INTERMEDIATESTANDS     2360
#define IDC_TREE_INTERMEDIATESTANDS     2361
#define IDC_RADIONEXTWAYPOINT           2362
#define IDC_RADIOHEADING                2363
#define IDC_EDITDEGREES                 2364
#define IDC_STATICDEGREE                2365
#define IDC_EDITVISDISTANCE             2366
#define IDC_STATICVISUAL                2367
#define IDC_SPIN_DEGREES                2368
#define IDC_SPIN_VISDISTANCE            2369
#define IDC_STATIC_PROPERTY             2370
#define IDC_STATIC_TYPE                 2371
#define IDC_STATIC_RUNWAY               2372
#define IDC_STATIC_MARK                 2373
#define IDC_STATIC_MinSpeedUnit         2374
#define IDC_STATIC_MaxSpeedUnit         2375
#define IDC_STATIC_MinHeightUnit        2376
#define IDC_STATIC_MaxHeightUnit        2377
#define IDC_EDIT_LANEWIDTH              2378
#define IDC_LANEWIDTH                   2378
#define IDC_EDIT_LANENUMBER             2379
#define IDC_LANENUMBER                  2379
#define IDC_COMBO_DRIVE                 2380
#define IDC_EDIT_RINGROADOFFSET         2381
#define IDC_SPIN_LANEWIDTH              2382
#define IDC_SPIN_LANENUMBER             2383
#define IDC_VIEW_SCHEDULE               2384
#define IDC_SPIN_FLTCOUNT               2385
#define IDC_STATIC_FLIGHTTYPE           2386
#define IDC_STATIC_DISANDTIME           2387
#define IDC_LIST_DISANDTIME             2388
#define IDC_STATIC_IMAGE                2389
#define IDC_TAB                         2390
#define IDC_STATIC_CREAT                2394
#define IDC_STATIC_DELETE               2395
#define IDC_STATIC_SAVE                 2396
#define IDC_BUTTON_TRIAL_SEPARATION_OK  2397
#define IDC_LIST3                       2398
#define IDC_STATIC_SECOND_RUNWAY        2399
#define IDC_SPIN_LANE                   2400
#define IDC_SPIN_NUM                    2401
#define IDC_LIST_BOX_OBJECT             2402
#define IDC_SCROLLBAR2                  2403
#define IDC_COMBOX_DATA                 2404
#define IDC_EDIT_RADIUS                 2405
#define IDC_EDIT_DIVUNDER               2406
#define IDC_EDIT_DIVOVER                2407
#define IDC_TOOLBAR_CONTROL             2408
#define IDC_SAVE_DATA                   2409
#define IDC_SECTOR_LIST                 2410
#define IDC_STATIC_CLASS                2411
#define IDC_STATIC_RADIUS               2412
#define IDC_STATIC_NM                   2413
#define IDC_STATIC_CONVER               2414
#define IDC_STATIC_CONDEG               2415
#define IDC_STATIC_DIVOVER              2416
#define IDC_STATIC_DIVDEG               2417
#define IDC_STATIC_CRITERA              2418
#define IDC_STATIC_PROERTIES            2419
#define IDC_SPIN_RADIUS                 2420
#define IDC_STATIC_AIRROUTE_NAME        2421
#define IDC_EDIT_AIRROUTE_NAME          2422
#define IDC_STATIC_LEFT_INCLUDE         2423
#define IDC_STATIC_LEFT_SETTING         2424
#define IDC_STATIC_CONVERGENT           2425
#define IDC_STATIC_DEG1                 2426
#define IDC_STATIC_DIVERGENT            2427
#define IDC_STATIC_DEG2                 2428
#define IDC_STATIC_LIMIT                2429
#define IDC_STATIC_FT1                  2430
#define IDC_STATIC_FT2                  2431
#define IDC_STATIC_RIGHT_INCLUDE        2432
#define IDC_STATIC_STD                  2433
#define IDC_STATIC_LAHSO                2434
#define IDC_STATIC_CLEAR_TO_POS         2435
#define IDC_STATIC_SEC1                 2436
#define IDC_STATIC_ATR1                 2437
#define IDC_STATIC_NM2                  2438
#define IDC_STATIC_SEC2                 2439
#define IDC_STATIC_DTS1                 2440
#define IDC_STATIC_SEC3                 2441
#define IDC_STATIC_CLEAR_TO_IF_EX       2442
#define IDC_STATIC_CBASIS               2443
#define IDC_STATIC_INFO                 2445
#define IDC_TREE_WEATHER                2446
#define IDC_STATIC_PAD                  2447
#define IDC_STATIC_FLIGHT_TYPE          2448
#define IDC_RADIO_GATE                  2449
#define IDC_RADIO_DEICE                 2450
#define IDC_STATIC_WEATHER              2451
#define IDC_STATIC_FLIGHT               2452
#define IDC_STATIC_DEICE                2453
#define IDC_STATIC_TYPEFRAME            2454
#define IDC_STATIC_STAND                2455
#define IDC_TREE_ROUTEPATH              2457
#define IDC_RADIO_PATH                  2458
#define IDC_RADIO_ROUTE                 2459
#define IDC_STATIC_SECTORNAME           2462
#define IDC_CHECK_Flight                2463
#define IDC_CHECK_CONFLICT              2464
#define IDC_CHECK_DISTANCE              2465
#define IDC_CHECK_DEPARTURE             2466
#define IDC_CHECK_MAINTENACE            2467
#define IDC_STATIC_PRIORITY_SETTING     2468
#define IDC_COMBO_PRIRITY1              2469
#define IDC_COMBO_PRIRITY3              2472
#define IDC_COMBO_PRIRITY2              2473
#define IDC_COMBO_PRIRITY4              2474
#define IDC_TREE_SECTOR                 2475
#define IDC_STATIC_REQ                  2476
#define IDC_STATIC_NAME                 2477
#define IDC_STATIC_MESSAGE              2478
#define IDC_COMBO_HOLDPRIORITY          2479
#define IDC_BUTTON_DEL                  2480
#define IDC_BUTTON_CREATE2              2481
#define IDC_BUTTON_CREATE               2481
#define IDC_EDIT_FIX                    2482
#define IDC_STATIC_FIX                  2483
#define IDC_LIST_DEICEPAD               2484
#define IDC_STATIC_QUEUE                2485
#define IDC_STATIC_PATH                 2486
#define IDC_STATIC_NAME_VAL             2488
#define IDC_COMBO_FIX                   2489
#define ID_OK                           2490
#define IDC_OK                          2490
#define IDC_TREE_ACCATEGORY             2491
#define IDC_TREE_SECTORLIMITATION       2492
#define IDC_STATIC_STAR                 2495
#define IDC_TREE_FLIGHTTYPE             2496
#define IDC_STATIC_RUNWAYTOOLBAR        2497
#define IDC_LIST_RUNWAYPORT             2498
#define IDC_TREE_SELECT                 2499
#define IDC_TREE_FLIGHTTYPE_TIME        2500
#define IDC_STATIC_EXIT                 2501
#define IDC_COMBO_ROUTECHOICE           2502
#define IDC_STATIC_FlIGHTTOOLBAR        2503
#define IDC_STATIC_FLIGHTTY             2504
#define IDC_STATIC_ORIGDEST_TOOLBAR     2504
#define IDC_CHECK_ENROUTE               2505
#define IDC_CHECK_ARR                   2506
#define IDC_CHECK_DEP                   2507
#define IDC_STATIC_ROUTEASSIGN_TOOLBAR  2507
#define IDC_BUTTON_DEPTIMEWINDOW        2508
#define IDC_EDIT_DEPTIMEWINDOW          2509
#define IDC_COMBO_ARRDISTRIBUTION       2510
#define IDC_COMBO_ORIGIN                2511
#define IDC_COMBO_DEST                  2512
#define IDC_COMBO_ACTYPE                2513
#define IDC_COMBO_CODE                  2514
#define IDC_CHECK_DIABLESETTINGS        2515
#define IDC_STATIC_VEHICLEFRAME         2516
#define IDC_TREE_TYPETREE               2517
#define IDC_LIST_TAXIWAYLIST            2518
#define IDC_STATIC_TAXIWAYTOOLABR       2519
#define IDC_STAND_CRITERIA              2520
#define IDC_STATIC_SHOW                 2521
#define IDC_STATIC_RUNWAYLST            2522
#define IDC_STATIC_TOOL                 2523
#define IDC_TREE_HOLD_SHORTLINE         2524
#define IDC_LIST_ROUTENAME              2525
#define IDC_STATIC_NAMETEXT             2526
#define IDC_TREE_VIEW                   2527
#define IDC_TREE_DEICEPADS              2528
#define IDC_STATIC_MAINFRAME            2529
#define IDC_TREE_RELEASEPOINT           2530
#define IDC_STATIC_FIRSTRUNWAY          2531
#define IDC_RADIO_PROB_BASED            2532
#define IDC_RADIO_PRIO_BASED            2533
#define IDC_TREE_TAXIWAY                2535
#define IDC_LIST_CONSTRAINTS            2536
#define IDC_STATIC_TAXIWAY              2537
#define IDC_STATIC_CONSTRAINTS          2538
#define IDC_TREE_TAXIWAYFAMILY          2539
#define IDC_TREE_PRIORITY               2540
#define IDC_STATIC_ROUTECHOICE          2541
#define IDC_TIME                        2542
#define IDC_STATIC_FROM                 2543
#define IDC_STATIC_TO                   2544
#define IDC_STATIC_DESCRIPTION          2545
#define IDC_STATIC_ORIGDEST             2546
#define IDC_STATIC_ORG                  2547
#define IDC_STATIC_DST                  2548
#define IDC_TREE_ORDER                  2551
#define IDC_LIST_NAME                   2554
#define IDC_COMBO_TAXIWAY               2555
#define IDC_COMBO_START                 2556
#define IDC_COMBO_END                   2557
#define ID_TOOLBAR_ADD                  32771
#define ID_TOOLBAR_DEL                  32772
#define ID_TOOLBAR_EDIT                 32773
#define ID_BUTTON32774                  32774
#define ID_ATCSEPARATION_EDIT           32776
#define ID_ATCSEPARATION_DELETE         32777
#define ID_ATCRWPAIR_NEW                32778
#define ID_ATCRWPAIR_EDIT               32779
#define ID_ATCRWPAIR_DELETE             32780
#define ID_ATCSEPARATION_NEW            32781
#define ID_WEATHER_NEW                  32782
#define ID_WEATHER_DELETE               32783
#define ID_ATCSEARATION_DELETE          32783
#define ID_EDIT_WEATHERTIME             32784
#define ID_NEW_WEATHERTIME              32785
#define ID_DEL_WEATHERTIME              32786
#define ID_BUTTON32790                  32790
#define ID_ADD_NECR                     32795
#define ID_ADD_NECA                     32796
#define ID_ADD_ARAIRROUTE               32797
#define ID_DEL_ARAIRROUTE               32798
#define ID_DEL_NECR                     32803
#define ID_DEL_NECA                     32804
#define ID_TOOLBAR_RUNWAY_ADD           32805
#define ID_TOOLBAR_RUNWAY_DEL           32806
#define ID_TOOLBAR_RUNWAY_EDIT          32807
#define ID_TOOLBAR_TAXIWAY_ADD          32808
#define ID_TOOLBAR_TAXIWAY_DEL          32809
#define ID_TOOLBAR_TAXIWAY_EDIT         32810
#define ID_TAXIINBOUND_NEW              32813
#define ID_BUTTON32814                  32814
#define ID_TAXIINBOUND_DEL              32814
#define ID_TOOLBAR_ADD_RUNWAY           32815
#define ID_NEW_ARWAYPOINT               32817
#define ID_EDIT_ARWAYPOINT              32818
#define ID_DEL_ARWAYPOINT               32819
#define ID_Menu                         32820
#define ID__DELETESECTOR                32822
#define ID_ADDSECTOR                    32823
#define ID__FFFFF                       32825
#define ID__FFFF                        32826
#define ID__FFFF32827                   32827
#define ID__FFF32828                    32828
#define ID__FFF32829                    32829
#define ID__FFF32830                    32830
#define ID__FFF32831                    32831
#define ID__FFF32832                    32832
#define ID__FFF32833                    32833
#define ID__FFFF32834                   32834
#define ID_ADD_TIMERANGE                32835
#define ID_DEL_TIMERANGE                32836
#define ID_EDIT_TIMERANGE               32837
#define ID_FLTTYPE_NEW                  32838
#define ID_FLTTYPE_DEL                  32839
#define ID_FLTTYPE_EDIT                 32840
#define ID_BUTTON32841                  32841
#define ID_BUTTON32842                  32842
#define ID_BUTTON32843                  32843
#define ID_BUTTON32844                  32844
#define ID_NEW_APPROCHRUNWAY            32845
#define ID_DEL_APPROCHRUNWAY            32846
#define ID_EDIT_APPROCHRUNWAY           32847
#define ID_TOOLBAR_VECHILE_ADD          32848
#define ID_TOOLBAR_VECHILE_DEL          32849
#define ID_TOOLBAR_VERCHILE_EDIT        32850
#define ID_EDIT_MENUITEM                32855
#define ID_DELETE_MENUITEM              32856
#define ID_NEW_MENULIST                 32857
#define ID_NEW_MENU                     32858
#define ID_DELETE_MENU                  32859
#define ID_EDIT_MENU                    32860
#define ID_TOOLB_ADD                    32863
#define ID_FLTREL_ADD                   32863
#define ID_FLTREL_DEL                   32864
#define ID_DEL_MENU                     32865
#define ID_BUTTON32866                  32866
#define ID_DEPSLOT_EDIT                 32866
#define ID_DEPSLOT_ADD                  32867
#define ID_DEPSLOT_DEL                  32868
#define ID_IMPORT_BROWSE                32869
#define ID_IMPORT_DEL                   32871
#define ID_DIRCONS_ADD                  32875
#define ID_DIRCONS_DEL                  32876
#define ID_BUTTON32877                  32877
#define ID_INSERT_ARWAYPOINT            32877
#define ID_APPROACH_ADD                 32878
#define ID_APPROACH_DEL                 32879
#define ID_APPROACH_EDIT                32880
#define ID_BUTTON32881                  32881
#define ID_BUTTON_CREATE                32881
#define ID_BUTTON32882                  32882
#define ID_BUTTON_CANCEL                32882
#define ID_BUTTON_DELETE                32882
#define ID_BUTTON32883                  32883
#define ID_Approach                     32888
#define ID_CRUISE                       32891
#define ID_Terminal                     32894
#define ID_ALL                          32895
#define ID_TOOLBAR_FLIGHT_TYPE_ADD      32896
#define ID_TOOLBAR_FLIGHT_TYPE_DEL      32897
#define ID_TOOLBAR_PAD_ADD              32899
#define ID_TOOLBAR_PAD_DEL              32900
#define ID_TOOLBAR_FLIGHT_TYPE_EDIT     32901
#define ID_TOOLBAR_INTRAIL_ADD          32902
#define ID_TOOLBAR_INTRAIL_DEL          32903
#define ID_TOOLBAR_INTRAIL_EDIT         32904
#define ID_BACKTRACK                    32907
#define ID_NOBACKTRACK                  32908
#define ID_TAKEOFFPOS_NOBACKTRACK       32911
#define ID_TAKEOFFPOS_MAXBACKTRACK      32914
#define ID_TAKEOFFPOS_MINBACKTRACK      32915
#define ID_TOOLBAR_QUEUE_ADD            32916
#define ID_TOOLBAR_QUEUE_DEL            32917
#define ID_STANDBUFFER_ADD              32918
#define ID_STANDBUFFER_DEL              32919
#define ID_STANDBUFFER_EDIT             32920
#define ID__ADDROUTEWAY                 32921
#define ID__DEL                         32922
#define ID_TOOLBAR_VEHICULAR_TAXIWAY_ADD 32923
#define ID_TOOLBAR_VEHICULAR_TAXIWAY_DEL 32924
#define ID_TOOLBAR_ADDTAXIWAY           32925
#define ID_TOOLBAR_DELTAXIWAY           32926
#define ID_FLIGHTTYPE_ADD               32928
#define ID_FLIGHTTYPE_EDIT              32931
#define ID_FLIGHTTYPE_REMOVE            32932
#define ID_NEW_ARCWAYPOINT              32933
#define ID_TOOLBAR_WAYPOINT_ADD         32934
#define ID_TOOLBAR_WAYPOINT_DEL         32935
#define ID_BUTTON_ADD                   32936
#define ID_BUTTON_DEL                   32937
#define ID_BUTTON32939                  32939
#define ID_BUTTON_NEW                   32940
#define ID_BUTTON_ADDSURFACE            32940
#define ID_BUTTON_NEWCONDITION          32940
#define ID_BUTTON32943                  32943
#define ID_ADD_STAND                    32945
#define ID_EDIT_STAND                   32948
#define ID_DEL_STAND                    32949
#define ID_DEICE_PAD                    32954
#define ID_DEP_STAND                    32955
#define ID_LEAD_OUTLINE                 32956
#define ID_REMOTE_STAND                 32957
#define ID_BUTTON_NEW_EVENT             32958
#define ID_BUTTON_DELSURFACE            32959
#define ID_TOOLBARBUTTONADD             32961
#define ID_MOVETOP                      32962
#define ID_MOVEBOTTOM                   32963
#define ID_ADD_EXIT_PRIORITY            32965
#define ID_DEL_EXIT_PRIORITY            32966
#define ID_IDR_SEP                      32967
#define ID_FLIGHTTYPE_ADDFLIGHTTYPE     32968
#define ID_FLIGHTTYPE_EDITFLIGHTTYPE    32969
#define ID_FLIGHTTYPE_DELETEFLIGHTTYPE  32970
#define ID_MENU_NEWPRIORITYRWY          32975
#define ID_MENU_NEWTAKEOFFPOS           32977
#define ID_TAKEOFFFLTTIME_NEWDEPSTANDFAMILY 32978
#define ID_TAKEOFFFLTTIME_NEWFLIGHTTYPE 32979
#define ID_TAKEOFFFLTTIME_NEWTIMERANGE  32980
#define ID_PEOPLEMOVER_NEW              32981
#define ID_PEOPLEMOVER_DELETE           32982
#define ID_STANDPOPMENU_DELETE          32983
#define ID_STANDPOPMENU_EDIT            32984
#define ID_STANDPOPMENU_NEWFLIGHTTYPE   32986
#define ID_FLIGHTTYPEPOPMENU_EDIT       32987
#define ID_FLIGHTTYPEPOPMENU_DELETE     32988
#define ID_FLIGHTTYPEPOPMENU_NEWTIMEWINDOW 32989
#define ID_TOOLBARBUTTONDEL             32989
#define ID_TOOLBARBUTTONEDIT            32990
#define ID_MENU_NEWDEPSTAND             32991
#define ID_TIMEPOPMENU_EDIT             32992
#define ID_TIMEPOPMENU_DELETE           32993
#define ID_RUNWAYPOPMENU_EDIT           32995
#define ID_RUNWAYPOPMENU_DELETE         32996
#define ID_TAKEOFFPOSPOPMENU_EDITPOS    33003
#define ID_TAKEOFFPOSPOPMENU_DELETEPOS  33004
#define ID_ADDFLIGHTTYPE                33005
#define ID_TOOLBAR_WINGSPAN_ADJCONS_ADD 33005
#define ID_                             33006
#define ID_TOOLBAR_WINGSPAN_ADJCONS_DEL 33006
#define ID_TOOLBAR_WINGSPAN_ADJCONS_EDIT 33007
#define ID_EDIT_FLIGTHTYPE              33008
#define ID_DELETE_FLIGHTTYPE            33009
#define ID__DELETE_TIMERANGE            33013
#define ID__EDIT_TIMERANGE              33014
#define ID__ADD_TIMERANGE               33015
#define ID_ADD_STANDGROUP               33016
#define ID_DELETE_STANDGROUP            33017
#define ID_EDIT_STANDGROUP              33018
#define IDR_MENU_ADD_PARKINGSTANDS      33020
#define ID_MENU_ADD_PARKINGSTANDS       33021
#define ID__ADDNEWPARKINGSTANDS         33022
#define ID_ADD_PARKINGSTANDS            33023
#define ID_Menu33027                    33027
#define ID_ADD_FLIGHTTYPE               33029
#define ID_ADD_TIMEWINDOW               33030
#define ID_TOOLBARBUTTONUP              33031
#define ID_TOOLBARBUTTONDOWN            33032
#define ID_POPMENU_ADD_INTERSECTION     33034
#define ID_POPMENU_INTERSECTION         33035
#define ID_Menu33036                    33036
#define ID_POPMENU_DEL_INTERSECTION     33037
#define IDR_DELINTERSECTION             33038
#define ID_FLIGHTSTYPEPOPUPMENU_EDIT    33042
#define ID_FLIGHTSTYPEPOPUPMENU_DELETE  33043
#define ID_FLIGHTSTYPEPOPUPMENU_NEWTIMEWINDOW 33044
#define ID_TIMERANGEPOPUPMENU_EDIT      33045
#define ID_TIMERANGEPOPUPMENU_NEWTAKEOFFPOSITION 33047
#define ID_TAKEOFFPOSITIONPOPUPMENU_EDLT 33048
#define ID_TIMERANGEPOPUPMENU_DELET     33050
#define ID_TAKEOFFPOSITION_DELETE       33054
#define ID_TAKEOFFPOSITION_EDIT         33055
#define ID_BUTTON_UP                    33080
#define ID_BUTTON_DOWN                  33081
#define ID_BUTTON_EDIT                  33082
#define IDC_EDIT7                       33083
#define IDC_EDIT8                       33084
#define IDC_SPIN11                      33085
#define IDC_EDIT9                       33086
#define IDC_SPIN12                      33087
#define IDD_DIALOG_GOAROUNDCRITERIA     33088
#define ID_BUTTONUP                     35150
#define ID_BUTTONDOWN                   35151
#define IDC_STATIC_SIDESTEPTORUNWAY     65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2279
#define _APS_NEXT_COMMAND_VALUE         33056
#define _APS_NEXT_CONTROL_VALUE         2558
#define _APS_NEXT_SYMED_VALUE           2338
#endif
#endif
