md .\Common\
md .\Engine\
md .\Inputs\
md .\Results\
copy /y /d D:\Work\mainline\src\Common\CATEGORY.H .\Common\
copy /y /d D:\Work\mainline\src\Common\CONSTRNT.H .\Common\
copy /y /d D:\Work\mainline\src\Common\containr.h .\Common\
copy /y /d D:\Work\mainline\src\Common\csv_file.h .\Common\
copy /y /d D:\Work\mainline\src\Common\DATASET.H .\Common\
copy /y /d D:\Work\mainline\src\Common\FLT_CNST.H .\Common\
copy /y /d D:\Work\mainline\src\Common\strdict.h .\Common\
copy /y /d D:\Work\mainline\src\Common\TERM_BIN.H .\Common\
copy /y /d D:\Work\mainline\src\Common\TERMFILE.H .\Common\
copy /y /d D:\Work\mainline\src\Common\CATEGORY.CPP .\Common\
copy /y /d D:\Work\mainline\src\Common\CONSTRNT.CPP .\Common\
copy /y /d D:\Work\mainline\src\Common\containr.CPP .\Common\
copy /y /d D:\Work\mainline\src\Common\csv_file.CPP .\Common\
copy /y /d D:\Work\mainline\src\Common\DATASET.CPP .\Common\
copy /y /d D:\Work\mainline\src\Common\FLT_CNST.CPP .\Common\
copy /y /d D:\Work\mainline\src\Common\strdict.cpp .\Common\
copy /y /d D:\Work\mainline\src\Common\TERM_BIN.CPP .\Common\
copy /y /d D:\Work\mainline\src\Common\TERMFILE.CPP .\Common\
copy /y /d D:\Work\mainline\src\Engine\ASSEVENT.CPP .\Engine\
copy /y /d D:\Work\mainline\src\Engine\BAGENTER.CPP .\Engine\
copy /y /d D:\Work\mainline\src\Engine\BOARDCAL.CPP .\Engine\
copy /y /d D:\Work\mainline\src\Engine\ENTRY.CPP .\Engine\
copy /y /d D:\Work\mainline\src\Engine\GREET.CPP .\Engine\
copy /y /d D:\Work\mainline\src\Engine\MOBILE.CPP .\Engine\
copy /y /d D:\Work\mainline\src\Engine\MOVEVENT.CPP .\Engine\
copy /y /d D:\Work\mainline\src\Engine\PROCQ.CPP .\Engine\
copy /y /d D:\Work\mainline\src\Engine\SEQUENCQ.CPP .\Engine\
copy /y /d D:\Work\mainline\src\Engine\ASSEVENT.H .\Engine\
copy /y /d D:\Work\mainline\src\Engine\BAGENTER.H .\Engine\
copy /y /d D:\Work\mainline\src\Engine\BOARDCAL.H .\Engine\
copy /y /d D:\Work\mainline\src\Engine\ENTRY.H .\Engine\
copy /y /d D:\Work\mainline\src\Engine\FIXEDQ.H .\Engine\
copy /y /d D:\Work\mainline\src\Engine\GREET.H .\Engine\
copy /y /d D:\Work\mainline\src\Engine\MOBILE.H .\Engine\
copy /y /d D:\Work\mainline\src\Engine\MOVEVENT.H .\Engine\
copy /y /d D:\Work\mainline\src\Engine\NFIXEDQ.H .\Engine\
copy /y /d D:\Work\mainline\src\Engine\PROCQ.H .\Engine\
copy /y /d D:\Work\mainline\src\Engine\SEQUENCQ.H .\Engine\
copy /y /d D:\Work\mainline\src\Inputs\BAGDATA.CPP .\Inputs\
copy /y /d D:\Work\mainline\src\Inputs\BAGDATA.H .\Inputs\
copy /y /d D:\Work\mainline\src\Inputs\CON_DB.H .\Inputs\
copy /y /d D:\Work\mainline\src\Inputs\IN_TERM.H .\Inputs\
copy /y /d D:\Work\mainline\src\Inputs\PAXDIST.H .\Inputs\
copy /y /d D:\Work\mainline\src\Inputs\PAX_CNST.H .\Inputs\
copy /y /d D:\Work\mainline\src\Inputs\PROCDB.H .\Inputs\
copy /y /d D:\Work\mainline\src\Inputs\PROCHRCH.H .\Inputs\
copy /y /d D:\Work\mainline\src\Inputs\SECTLIST.H .\Inputs\
copy /y /d D:\Work\mainline\src\Inputs\CON_DB.CPP .\Inputs\
copy /y /d D:\Work\mainline\src\Inputs\IN_TERM.CPP .\Inputs\
copy /y /d D:\Work\mainline\src\Inputs\PAXDIST.CPP .\Inputs\
copy /y /d D:\Work\mainline\src\Inputs\PAX_CNST.CPP .\Inputs\
copy /y /d D:\Work\mainline\src\Inputs\PROCDB.CPP .\Inputs\
copy /y /d D:\Work\mainline\src\Inputs\PROCHRCH.CPP .\Inputs\
copy /y /d D:\Work\mainline\src\Inputs\SECTLIST.CPP .\Inputs\
copy /y /d D:\Work\mainline\src\Results\BAGENTRY.H .\Results\
copy /y /d D:\Work\mainline\src\Results\BAGLOG.H .\Results\
copy /y /d D:\Work\mainline\src\Results\BASELOG.H .\Results\
copy /y /d D:\Work\mainline\src\Results\EVENTLOG.H .\Results\
copy /y /d D:\Work\mainline\src\Results\FLTENTRY.H .\Results\
copy /y /d D:\Work\mainline\src\Results\FLTLOG.H .\Results\
copy /y /d D:\Work\mainline\src\Results\LOGITEM.H .\Results\
copy /y /d D:\Work\mainline\src\Results\PAXENTRY.H .\Results\
copy /y /d D:\Work\mainline\src\Results\PAXLOG.H .\Results\
copy /y /d D:\Work\mainline\src\Results\PROCLOG.H .\Results\
copy /y /d D:\Work\mainline\src\Results\PROCNTRY.H .\Results\
copy /y /d D:\Work\mainline\src\Results\BAGENTRY.CPP .\Results\
copy /y /d D:\Work\mainline\src\Results\BAGLOG.CPP .\Results\
copy /y /d D:\Work\mainline\src\Results\BASELOG.CPP .\Results\
copy /y /d D:\Work\mainline\src\Results\EVENTLOG.CPP .\Results\
copy /y /d D:\Work\mainline\src\Results\FLTENTRY.CPP .\Results\
copy /y /d D:\Work\mainline\src\Results\FLTLOG.CPP .\Results\
copy /y /d D:\Work\mainline\src\Results\LOGITEM.CPP .\Results\
copy /y /d D:\Work\mainline\src\Results\PAXENTRY.CPP .\Results\
copy /y /d D:\Work\mainline\src\Results\PAXLOG.CPP .\Results\
copy /y /d D:\Work\mainline\src\Results\PROCLOG.CPP .\Results\
copy /y /d D:\Work\mainline\src\Results\PROCNTRY.CPP .\Results\